// Mock client-side data for the logged-in user — will be replaced by Supabase queries

export const myOrders = [
  {
    id: "ORD-1024",
    date: "28 Jun 2026",
    product: "Robe Kaba Wax Maxi",
    image: "/plate-women.png",
    size: "M",
    qty: 1,
    amount: "62 200 FCFA",
    status: "Livré",
    timeline: [
      { label: "Commande passée",   date: "28 Jun · 09:14", done: true },
      { label: "Paiement confirmé", date: "28 Jun · 09:16", done: true },
      { label: "En préparation",    date: "29 Jun · 10:30", done: true },
      { label: "Expédiée",          date: "30 Jun · 14:00", done: true },
      { label: "Livrée",            date: "2 Jul · 11:45",  done: true },
    ],
    shipping: { carrier: "Colissimo", tracking: "6C14835X76543", address: "12 rue des Fleurs, 75011 Paris" },
    subtotal: "59 000 FCFA",
    shippingCost: "3 200 FCFA",
  },
  {
    id: "ORD-1020",
    date: "24 Jun 2026",
    product: "Robe Kaba Wax Maxi",
    image: "/plate-women.png",
    size: "M",
    qty: 1,
    amount: "62 200 FCFA",
    status: "Livré",
    timeline: [
      { label: "Commande passée",   date: "24 Jun · 15:02", done: true },
      { label: "Paiement confirmé", date: "24 Jun · 15:04", done: true },
      { label: "En préparation",    date: "25 Jun · 09:00", done: true },
      { label: "Expédiée",          date: "26 Jun · 11:00", done: true },
      { label: "Livrée",            date: "28 Jun · 10:20", done: true },
    ],
    shipping: { carrier: "Colissimo", tracking: "6C14835X11122", address: "12 rue des Fleurs, 75011 Paris" },
    subtotal: "59 000 FCFA",
    shippingCost: "3 200 FCFA",
  },
  {
    id: "ORD-1015",
    date: "10 May 2026",
    product: "Ensemble Enfant Wax",
    image: "/plate-kids.png",
    size: "6 ans",
    qty: 2,
    amount: "72 400 FCFA",
    status: "Livré",
    timeline: [
      { label: "Commande passée",   date: "10 Mai · 11:00", done: true },
      { label: "Paiement confirmé", date: "10 Mai · 11:02", done: true },
      { label: "En préparation",    date: "11 Mai · 08:30", done: true },
      { label: "Expédiée",          date: "12 Mai · 13:00", done: true },
      { label: "Livrée",            date: "14 Mai · 09:50", done: true },
    ],
    shipping: { carrier: "Colissimo", tracking: "6C14835X99211", address: "12 rue des Fleurs, 75011 Paris" },
    subtotal: "66 000 FCFA",
    shippingCost: "6 400 FCFA",
  },
];

export const mySurMesure = [
  {
    id: "SM-007",
    piece: "Robe Kaba",
    wax: "Caramel Atelier",
    col: "Col Mao",
    manches: "Sans manches",
    doublure: "Doublure simple",
    boutons: false,
    poches: "Poches latérales cachées",
    note: "J'aimerais une broderie dorée sur l'encolure.",
    status: "En production",
    date: "22 Jun 2026",
    deadline: "20 Jul 2026",
    devis: "145 000 FCFA",
    acompte: "72 500 FCFA",
    acomptePaid: true,
    pipeline: [
      { label: "Demande reçue",     done: true,  date: "22 Jun 2026" },
      { label: "Devis envoyé",      done: true,  date: "23 Jun 2026" },
      { label: "Acompte reçu",      done: true,  date: "24 Jun 2026" },
      { label: "En production",     done: true,  date: "25 Jun 2026" },
      { label: "Essayage / Retouche", done: false, date: null },
      { label: "Livraison",         done: false, date: null },
    ],
  },
  {
    id: "SM-003",
    piece: "Boubou",
    wax: "Indigo Royale",
    col: "Col rond",
    manches: "Manches longues",
    doublure: "Sans doublure",
    boutons: true,
    typeBouton: "Boutons dorés",
    poches: "Sans poches",
    note: "",
    status: "Devis envoyé",
    date: "28 Jun 2026",
    deadline: "30 Jul 2026",
    devis: "185 000 FCFA",
    acompte: "92 500 FCFA",
    acomptePaid: false,
    pipeline: [
      { label: "Demande reçue",       done: true,  date: "28 Jun 2026" },
      { label: "Devis envoyé",        done: true,  date: "29 Jun 2026" },
      { label: "Acompte reçu",        done: false, date: null },
      { label: "En production",       done: false, date: null },
      { label: "Essayage / Retouche", done: false, date: null },
      { label: "Livraison",           done: false, date: null },
    ],
  },
];

export const statusColors: Record<string, { bg: string; color: string }> = {
  "Livré":          { bg: "#d1fae5", color: "#065f46" },
  "En cours":       { bg: "#fdf5e8", color: "#b08a4a" },
  "Expédié":        { bg: "#dbeafe", color: "#1e40af" },
  "Annulé":         { bg: "#fee2e2", color: "#991b1b" },
  "Devis envoyé":   { bg: "#fdf5e8", color: "#b08a4a" },
  "En production":  { bg: "#ede9fe", color: "#5b21b6" },
  "Essayage":       { bg: "#dbeafe", color: "#1e40af" },
  "Reçu":           { bg: "#f3f4f6", color: "#6B7280" },
  "Terminé":        { bg: "#d1fae5", color: "#065f46" },
};
